Repository lambertjamesd/portal64, pull requests merged in 2023-10, with the labels that each got.

#258 Various Tweaks to Portal Gun Mechanics
  src/audio/clips.c
  src/audio/clips.h
  src/controls/controller_actions.c
  src/controls/controller_actions.h
  src/scene/portal_gun.c
  src/scene/portal_gun.h
  src/scene/scene.c
Labels: enhancement

#263 Added Subtitles to Game
  assets/closecaption_english.txt
  assets/test_chambers/test_chamber_00/test_chamber_00.yaml
  assets/test_chambers/test_chamber_01/test_chamber_01.yaml
  assets/test_chambers/test_chamber_02/test_chamber_02.yaml
  assets/test_chambers/test_chamber_03/test_chamber_03.yaml
  assets/test_chambers/test_chamber_04/test_chamber_04.yaml
  assets/test_chambers/test_chamber_05/test_chamber_05.yaml
  assets/test_chambers/test_chamber_06/test_chamber_06.yaml
  assets/test_chambers/test_chamber_07/test_chamber_07.yaml
  src/levels/cutscene_runner.c
  src/levels/cutscene_runner.h
  src/levels/level_definition.h
  src/menu/audio_options.c
  src/menu/audio_options.h
  src/menu/controls.c
  src/menu/controls.h
  src/savefile/savefile.h
  src/scene/hud.c
  src/scene/hud.h
  src/scene/security_camera.c
  tools/level_scripts/trigger.lua
Labels: enhancement

#261 Game Options Menu Tweaks
  src/menu/controls.c
  src/menu/gameplay_options.c
  src/menu/gameplay_options.h
  src/savefile/savefile.c
  src/savefile/savefile.h
  src/scene/dynamic_render_list.c
  src/scene/portal.h
  src/scene/render_plan.c
  src/scene/scene.c
Labels: bug, enhancement

#267 Add build support for supported audio languages
  Makefile
  README.md
  vpk/add_vpk_here.md
Labels: enhancement

#275 Dynamic Captions Building and Enhancements
  .gitignore
  Makefile
  README.md
  assets/closecaption_english.txt
  assets/fonts/dejavu_sans.png
  assets/fonts/dejavu_sans_book_8.json
  assets/test_chambers/test_chamber_00/test_chamber_00.yaml
  assets/test_chambers/test_chamber_01/test_chamber_01.yaml
  assets/test_chambers/test_chamber_02/test_chamber_02.yaml
  assets/test_chambers/test_chamber_03/test_chamber_03.yaml
  assets/test_chambers/test_chamber_04/test_chamber_04.yaml
  assets/test_chambers/test_chamber_05/test_chamber_05.yaml
  assets/test_chambers/test_chamber_06/test_chamber_06.yaml
  assets/test_chambers/test_chamber_07/test_chamber_07.yaml
  resource/.gitignore
  src/font/dejavusans.c
  src/levels/level_definition.h
  src/menu/audio_options.c
  src/menu/audio_options.h
  src/menu/controls.c
  src/menu/controls.h
  src/savefile/savefile.c
  src/savefile/savefile.h
  src/scene/hud.c
  src/scene/hud.h
  src/scene/security_camera.c
  src/scene/security_camera.h
  tools/level_scripts/subtitle_generate.py
Labels: enhancement

#287 Added in Volume Sliders And All Captions
  src/audio/soundplayer.c
  src/audio/soundplayer.h
  src/decor/decor_object.c
  src/levels/cutscene_runner.c
  src/menu/audio_options.c
  src/menu/audio_options.h
  src/menu/controls.c
  src/menu/controls.h
  src/menu/gameplay_options.c
  src/menu/joystick_options.c
  src/menu/landing_menu.c
  src/menu/load_game.c
  src/menu/main_menu.c
  src/menu/new_game_menu.c
  src/menu/save_game_menu.c
  src/menu/savefile_list.c
  src/player/player.c
  src/savefile/savefile.c
  src/savefile/savefile.h
  src/scene/ball.c
  src/scene/ball_catcher.c
  src/scene/ball_launcher.c
  src/scene/box_dropper.c
  src/scene/button.c
  src/scene/door.c
  src/scene/elevator.c
  src/scene/hud.c
  src/scene/hud.h
  src/scene/pedestal.c
  src/scene/scene.c
  src/scene/scene_animator.c
  src/scene/switch.c
  tools/level_scripts/subtitle_generate.py
Labels: enhancement

#293 Implement modular multi-audio-language support.
  .gitignore
  Makefile
  README.md
  src/levels/cutscene_runner.c
  src/locales/locales.c
  src/locales/locales.h
  src/menu/audio_options.c
  src/menu/audio_options.h
  src/savefile/savefile.c
  src/savefile/savefile.h
  tools/generate_sound_ids.js
  tools/level_scripts/subtitle_generate.py
Labels: enhancement

#295 Added Portal Funneling
  src/menu/gameplay_options.c
  src/menu/gameplay_options.h
  src/player/player.c
  src/savefile/savefile.c
  src/savefile/savefile.h
Labels: enhancement

#299 Audio Now Travels Through Portals
  src/audio/soundplayer.c
Labels: bug, enhancement

#304 Made Elevator to Wait for Voicelines to Move
  README.md
  src/levels/cutscene_runner.c
  src/levels/cutscene_runner.h
  src/scene/elevator.c
  src/scene/elevator.h
  src/scene/scene.c
  src/scene/scene.h
Labels: bug

#307 Fizzler is Anti-Portal
  src/physics/collision_scene.c
Labels: bug

#308 Ball Resets Lifetime Through Portal
  src/scene/ball.c
  src/scene/ball.h
Labels: bug

#303 Fixes Portal Height
  src/physics/collision_scene.c
  src/physics/collision_scene.h
  src/scene/portal.c
  src/scene/render_plan.c
Labels: bug

#309 fixed a soundplayer function call that broke build
  src/menu/gameplay_options.c
Labels: bug

#306 fixed glados voiceline pause in chamber 04
  assets/test_chambers/test_chamber_02/test_chamber_02.yaml
Labels: bug

#310 Fix slider issues
  src/menu/audio_options.c
  src/menu/gameplay_options.c
Labels: bug

#345 fix Makefile and update docs
  Makefile
  README.md
  vpk/add_vpk_here.md
Labels: documentation

#342 Fixes a save load crash and audio bug
  src/audio/soundplayer.c
  src/levels/cutscene_runner.c
  src/levels/levels.c
  src/menu/save_game_menu.c
Labels: severe bug

#367 Added music to appropriate levels
  README.md
  assets/sound/music/portal_self_esteem_fund.msox
  assets/sound/music/portal_subject_name_here.msox
  assets/sound/music/portal_taste_of_blood.msox
  assets/test_chambers/test_chamber_01/test_chamber_01.yaml
  assets/test_chambers/test_chamber_04/test_chamber_04.yaml
  assets/test_chambers/test_chamber_06/test_chamber_06.yaml
  assets/test_chambers/test_chamber_07/test_chamber_07.yaml
  src/levels/cutscene_runner.c
  src/levels/level_definition.h
  src/savefile/savefile.c
Labels: enhancement

#381 Added Ambient Sound to Game
  Makefile
  assets/sound/ambient/atmosphere/ambience_base.ins
  assets/test_chambers/test_chamber_00/test_chamber_00.yaml
  assets/test_chambers/test_chamber_01/test_chamber_01.yaml
  assets/test_chambers/test_chamber_02/test_chamber_02.yaml
  assets/test_chambers/test_chamber_03/test_chamber_03.yaml
  assets/test_chambers/test_chamber_04/test_chamber_04.yaml
  assets/test_chambers/test_chamber_05/test_chamber_05.yaml
  assets/test_chambers/test_chamber_06/test_chamber_06.yaml
  assets/test_chambers/test_chamber_07/test_chamber_07.yaml
  src/audio/soundplayer.c
  src/audio/soundplayer.h
  src/levels/cutscene_runner.c
Labels: enhancement

#385 Fix Door Object Collision Issue
  tools/level_scripts/world.lua
Labels: bug

#386 Fixes Player Clipping Issues
  src/player/player.c
Labels: bug

#393 Player can hold objects through portals recursively
  src/physics/collision_scene.c
  src/physics/raycasting.h
  src/player/player.c
  src/player/player.h
  src/scene/security_camera.c
Labels: enhancement
